change the config file

diff --git a/.github/workflows/stage-deploy.yml b/.github/workflows/stage-deploy.yml
--- a/.github/workflows/stage-deploy.yml
+++ b/.github/workflows/stage-deploy.yml
@@ -187,28 +187,28 @@ jobs:
         with:
           namespace: development
           k8-config-file-paths: |
-            manifest/stateful.yml
+            manifest/wordpress-apache2/stateful.yml
           replacement-method: defined
         env:
           IMAGE_TAG: ${{ steps.commit.outputs.version }}
           CHANGE_CAUSE: ${{ github.ref }}
       
-      # - name: Check deployment image
-      #   run: |
-      #     image='kubectl get sts -n development wordpress-site -o jsonpath="{..image}"'
-      #     if [ "$image" = "187451058634.dkr.ecr.ap-south-1.amazonaws.com/wordpress:${{ steps.commit.outputs.version }}" ]; then
-      #       echo "Image updated successfully"
-      #     else
-      #       echo "Image update failed"
-      #       exit 1
-      #     fi
+      - name: Check deployment image
+        run: |
+          image='kubectl get sts -n apache wp-apache -o jsonpath="{..image}"'
+          if [ "$image" = "187451058634.dkr.ecr.ap-south-1.amazonaws.com/wordpress-apache:${{ steps.commit.outputs.version }}" ]; then
+            echo "Image updated successfully"
+          else
+            echo "Image update failed"
+            exit 1
+          fi
 
       # Apply the updated StatefulSet to the Kubernetes cluster
       - name: Deploy to EKS
         run: |
           # Set the current context to the EKS cluster
           kubectl config get-contexts  
-          kubectl apply -f manifest/stateful.yml
+          kubectl apply -f manifest/wordpress-apache2/stateful.yml
 
   notify: 
     runs-on: ubuntu-latest
