revert changes

diff --git a/.github/workflows/stage-deploy.yml b/.github/workflows/stage-deploy.yml
--- a/.github/workflows/stage-deploy.yml
+++ b/.github/workflows/stage-deploy.yml
@@ -193,15 +193,15 @@ jobs:
           IMAGE_TAG: ${{ steps.commit.outputs.version }}
           CHANGE_CAUSE: ${{ github.ref }}
       
-      - name: Check deployment image
-        run: |
-          image='kubectl get sts -n apache wp-apache -o jsonpath="{..image}"'
-          if [ "$image" = "187451058634.dkr.ecr.ap-south-1.amazonaws.com/wordpress-apache:${{ steps.commit.outputs.version }}" ]; then
-            echo "Image updated successfully"
-          else
-            echo "Image update failed"
-            exit 1
-          fi
+      # - name: Check deployment image
+      #   run: |
+      #     image='kubectl get sts -n apache wp-apache -o jsonpath="{..image}"'
+      #     if [ "$image" = "187451058634.dkr.ecr.ap-south-1.amazonaws.com/wordpress-apache:${{ steps.commit.outputs.version }}" ]; then
+      #       echo "Image updated successfully"
+      #     else
+      #       echo "Image update failed"
+      #       exit 1
+      #     fi
 
       # Apply the updated StatefulSet to the Kubernetes cluster
       - name: Deploy to EKS
